import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('vpxEditor', {
  onTableLoaded: callback => ipcRenderer.on('table-loaded', (event, data) => callback(data)),
  onTableClosed: callback => ipcRenderer.on('table-closed', () => callback()),
  onExtractedDirChanged: callback => ipcRenderer.on('extracted-dir-changed', (event, dir) => callback(dir)),
  onLoading: callback => ipcRenderer.on('loading', (event, data) => callback(data)),
  onStatus: callback => ipcRenderer.on('status', (event, message) => callback(message)),
  onZoomIn: callback => ipcRenderer.on('zoom-in', () => callback()),
  onZoomOut: callback => ipcRenderer.on('zoom-out', () => callback()),
  onSetTheme: callback => ipcRenderer.on('set-theme', (event, theme) => callback(theme)),
  onSelectItem: callback => ipcRenderer.on('select-item', (event, itemName) => callback(itemName)),
  onSelectItems: callback => ipcRenderer.on('select-items', (event, itemNames) => callback(itemNames)),
  notifySelectionChanged: selectedItems => ipcRenderer.send('notify-selection-changed', selectedItems),
  onSelectionChanged: callback =>
    ipcRenderer.on('selection-changed', (event, selectedItems) => callback(selectedItems)),
  onRequestSelectionResend: callback => ipcRenderer.on('request-selection-resend', () => callback()),
  onCollectionCreateFromSelectionRequest: callback =>
    ipcRenderer.on('collection-create-from-selection-request', () => callback()),
  onImagesChanged: callback => ipcRenderer.on('images-changed', () => callback()),
  onMaterialsChanged: callback => ipcRenderer.on('materials-changed', () => callback()),
  onSoundsChanged: callback => ipcRenderer.on('sounds-changed', () => callback()),
  onInfoChanged: callback => ipcRenderer.on('info-changed', (event, info) => callback(info)),
  onGamedataChanged: callback => ipcRenderer.on('gamedata-changed', (event, gamedata) => callback(gamedata)),
  onGameitemsChanged: callback => ipcRenderer.on('gameitems-changed', (event, gameitems) => callback(gameitems)),
  onScriptChanged: callback => ipcRenderer.on('script-changed', () => callback()),
  onViewSettingsChanged: callback => ipcRenderer.on('view-settings-changed', (event, settings) => callback(settings)),
  onToggleBackglassView: callback => ipcRenderer.on('toggle-backglass-view', (event, enabled) => callback(enabled)),
  onTableLockChanged: callback => ipcRenderer.on('table-lock-changed', (event, isLocked) => callback(isLocked)),
  toggleTableLock: () => ipcRenderer.send('toggle-table-lock'),
  onShowCloseConfirm: callback => ipcRenderer.on('show-close-confirm', () => callback()),
  closeConfirmResult: result => ipcRenderer.send('close-confirm-result', result),
  onShowWorkFolderModal: callback => ipcRenderer.on('show-work-folder-modal', (event, data) => callback(data)),
  workFolderModalResult: result => ipcRenderer.send('work-folder-modal-result', result),
  onInsertItem: callback => ipcRenderer.on('insert-item', (event, itemType) => callback(itemType)),
  onShowInfoModal: callback => ipcRenderer.on('show-info-modal', (event, data) => callback(data)),
  infoModalResult: () => ipcRenderer.send('info-modal-result'),
  onMeshImported: callback => ipcRenderer.on('mesh-imported', (event, data) => callback(data)),
  onUndo: callback => ipcRenderer.on('undo', () => callback()),
  onRedo: callback => ipcRenderer.on('redo', () => callback()),
  onCut: callback => ipcRenderer.on('cut', () => callback()),
  onCopy: callback => ipcRenderer.on('copy', () => callback()),
  onPaste: callback => ipcRenderer.on('paste', () => callback()),
  onPasteAtOriginal: callback => ipcRenderer.on('paste-at-original', () => callback()),
  onToggleLock: callback => ipcRenderer.on('toggle-lock', () => callback()),
  onDeleteSelected: callback => ipcRenderer.on('delete-selected', () => callback()),
  onSelectAll: callback => ipcRenderer.on('select-all', () => callback()),
  onUndoBegin: callback => ipcRenderer.on('undo-begin', (event, description) => callback(description)),
  onUndoEnd: callback => ipcRenderer.on('undo-end', () => callback()),
  onCollectionsUpdated: callback =>
    ipcRenderer.on('collections-updated', (event, collections) => callback(collections)),
  onUndoCancel: callback => ipcRenderer.on('undo-cancel', () => callback()),
  onUndoMarkImages: callback => ipcRenderer.on('undo-mark-images', () => callback()),
  onUndoMarkImageCreate: callback =>
    ipcRenderer.on('undo-mark-image-create', (event, imageName) => callback(imageName)),
  onUndoMarkImageDelete: callback =>
    ipcRenderer.on('undo-mark-image-delete', (event, imageName, imageData, filePath) =>
      callback(imageName, imageData, filePath)
    ),
  onUndoMarkMaterials: callback => ipcRenderer.on('undo-mark-materials', () => callback()),
  onUndoMarkMaterialCreate: callback =>
    ipcRenderer.on('undo-mark-material-create', (event, materialName) => callback(materialName)),
  onUndoMarkMaterialDelete: callback =>
    ipcRenderer.on('undo-mark-material-delete', (event, materialName, materialData) =>
      callback(materialName, materialData)
    ),
  onUndoMarkRenderProbes: callback => ipcRenderer.on('undo-mark-renderprobes', () => callback()),
  onUndoMarkRenderProbeCreate: callback =>
    ipcRenderer.on('undo-mark-renderprobe-create', (event, probeName) => callback(probeName)),
  onUndoMarkRenderProbeDelete: callback =>
    ipcRenderer.on('undo-mark-renderprobe-delete', (event, probeName, probeData) => callback(probeName, probeData)),
  onRenderProbesChanged: callback => ipcRenderer.on('renderprobes-changed', () => callback()),
  onUndoMarkForUndo: callback => ipcRenderer.on('undo-mark-for-undo', (event, itemName) => callback(itemName)),
  onUndoMarkGamedata: callback => ipcRenderer.on('undo-mark-gamedata', () => callback()),
  onUndoMarkInfo: callback => ipcRenderer.on('undo-mark-info', () => callback()),
  onUndoMarkGameitemsList: callback => ipcRenderer.on('undo-mark-gameitems-list', () => callback()),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  getViewSettings: () => ipcRenderer.invoke('get-view-settings'),
  getPanelSettings: () => ipcRenderer.invoke('get-panel-settings'),
  savePanelSettings: settings => ipcRenderer.invoke('save-panel-settings', settings),
  readFile: filePath => ipcRenderer.invoke('read-file', filePath),
  readBinaryFile: filePath => ipcRenderer.invoke('read-binary-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('write-file', filePath, content),
  listDir: dirPath => ipcRenderer.invoke('list-dir', dirPath),
  getImageInfo: imagePath => ipcRenderer.invoke('get-image-info', imagePath),
  importImage: () => ipcRenderer.invoke('import-image'),
  exportImage: (srcPath, suggestedName) => ipcRenderer.invoke('export-image', srcPath, suggestedName),
  deleteFile: filePath => ipcRenderer.invoke('delete-file', filePath),
  renameFile: (oldPath, newPath) => ipcRenderer.invoke('rename-file', oldPath, newPath),
  importMesh: primitiveFileName => ipcRenderer.invoke('import-mesh', primitiveFileName),
  browseObjFile: () => ipcRenderer.invoke('browse-obj-file'),
  meshImportResult: result => ipcRenderer.send('mesh-import-result', result),
  onShowAbout: callback => ipcRenderer.on('show-about', (event, data) => callback(data)),
  onInitSettings: callback => ipcRenderer.on('init-settings', (event, data) => callback(data)),
  onThemeChanged: callback => ipcRenderer.on('theme-changed', (event, theme) => callback(theme)),
  previewTheme: theme => ipcRenderer.send('preview-theme', theme),
  restoreTheme: theme => ipcRenderer.send('restore-theme', theme),
  onShowCollectionManager: callback => ipcRenderer.on('show-collection-manager', () => callback()),
  onShowTableInfo: callback => ipcRenderer.on('show-table-info', (event, data) => callback(data)),
  saveTableInfo: data => ipcRenderer.invoke('save-table-info', data),
  onInitDrawingOrder: callback => ipcRenderer.on('init-drawing-order', (event, data) => callback(data)),
  saveDrawingOrder: data => ipcRenderer.send('save-drawing-order', data),
  drawingOrderCancel: () => ipcRenderer.send('drawing-order-cancel'),
  onRequestDrawingOrderData: callback => ipcRenderer.on('request-drawing-order-data', (event, mode) => callback(mode)),
  sendDrawingOrderData: data => ipcRenderer.send('drawing-order-data', data),
  undoBegin: description => ipcRenderer.send('undo-begin', description),
  undoEnd: () => ipcRenderer.send('undo-end'),
  markDirty: () => ipcRenderer.send('mark-dirty'),
  markClean: () => ipcRenderer.send('mark-clean'),
  onMarkSavePoint: callback => ipcRenderer.on('mark-save-point', () => callback()),
  recordScriptChange: (before, after) => ipcRenderer.send('record-script-change', before, after),
  onRecordScriptChange: callback =>
    ipcRenderer.on('record-script-change', (event, before, after) => callback(before, after)),
  notifyScriptUndone: () => ipcRenderer.send('script-undone'),
  undoMarkInfo: () => ipcRenderer.send('undo-mark-info'),
  undoMarkGamedata: () => ipcRenderer.send('undo-mark-gamedata'),
  undoMarkGameitemsList: () => ipcRenderer.send('undo-mark-gameitems-list'),
  browseExecutable: name => ipcRenderer.invoke('browse-executable', name),
  checkFileExists: filePath => ipcRenderer.invoke('check-file-exists', filePath),
  saveSettings: settings => ipcRenderer.invoke('save-settings', settings),
  resetWindowBounds: () => ipcRenderer.send('reset-window-bounds'),
  onGridSizeChanged: callback => ipcRenderer.on('grid-size-changed', (event, gridSize) => callback(gridSize)),
  getGridSize: () => ipcRenderer.invoke('get-grid-size'),
  onTextureQualityChanged: callback => ipcRenderer.on('texture-quality-changed', (event, quality) => callback(quality)),
  getTextureQuality: () => ipcRenderer.invoke('get-texture-quality'),
  notifyBackglassViewChanged: enabled => ipcRenderer.send('backglass-view-changed', enabled),
  getEditorSettings: () => ipcRenderer.invoke('get-editor-settings'),
  onEditorSettingsChanged: callback =>
    ipcRenderer.on('editor-settings-changed', (event, settings) => callback(settings)),
  exportMesh: (primitiveFileName, suggestedName) => ipcRenderer.invoke('export-mesh', primitiveFileName, suggestedName),
  playTable: () => ipcRenderer.invoke('play-table'),
  onPlayStarted: callback => ipcRenderer.on('play-started', () => callback()),
  onPlayStopped: callback => ipcRenderer.on('play-stopped', () => callback()),
  onConsoleOpen: callback => ipcRenderer.on('console-open', () => callback()),
  onConsoleOutput: callback => ipcRenderer.on('console-output', (event, data) => callback(data)),
  onToggleConsole: callback => ipcRenderer.on('toggle-console', () => callback()),
  stopPlay: () => ipcRenderer.invoke('stop-play'),
  getConsoleSettings: () => ipcRenderer.invoke('get-console-settings'),
  saveConsoleSettings: settings => ipcRenderer.invoke('save-console-settings', settings),
  getVersion: () => ipcRenderer.invoke('get-version'),
  updateUndoState: state => ipcRenderer.send('update-undo-state', state),
  updateClipboardState: state => ipcRenderer.send('update-clipboard-state', state),
  onToggleMagnify: callback => ipcRenderer.on('toggle-magnify', () => callback()),
  notify3DModeChanged: enabled => ipcRenderer.send('3d-mode-changed', enabled),
  toggleScriptEditor: () => ipcRenderer.send('toggle-script-editor'),
  onScriptEditorOpened: callback => ipcRenderer.on('script-editor-opened', () => callback()),
  onScriptEditorClosed: callback => ipcRenderer.on('script-editor-closed', () => callback()),
  setClipboardData: data => ipcRenderer.invoke('set-clipboard-data', data),
  getClipboardData: () => ipcRenderer.invoke('get-clipboard-data'),
  hasClipboardData: () => ipcRenderer.invoke('has-clipboard-data'),
  openTransform: (type, data) => ipcRenderer.send('open-transform', type, data),
  onApplyTransform: callback => ipcRenderer.on('apply-transform', (event, data) => callback(data)),
  onUndoTransform: callback => ipcRenderer.on('undo-transform', () => callback()),
  onSaveTransform: callback => ipcRenderer.on('save-transform', (event, data) => callback(data)),
  onCancelTransform: callback => ipcRenderer.on('cancel-transform', () => callback()),
  onInitTransform: callback => ipcRenderer.on('init-transform', (event, data) => callback(data)),
  onSetInputDisabled: callback => ipcRenderer.on('set-input-disabled', (event, disabled) => callback(disabled)),
  onInitAbout: callback => ipcRenderer.on('init-about', (event, data) => callback(data)),
  onInitTableInfo: callback => ipcRenderer.on('init-table-info', (event, data) => callback(data)),
  saveTableInfoWindow: data => ipcRenderer.send('save-table-info-window', data),
  cancelTableInfo: () => ipcRenderer.send('cancel-table-info'),
  applyTransform: data => ipcRenderer.send('apply-transform', data),
  undoTransform: () => ipcRenderer.send('undo-transform'),
  saveTransform: data => ipcRenderer.send('save-transform', data),
  cancelTransform: () => ipcRenderer.send('cancel-transform'),
  onInitCollectionManager: callback => ipcRenderer.on('init-collection-manager', (event, data) => callback(data)),
  onCollectionsChanged: callback => ipcRenderer.on('collections-changed', (event, data) => callback(data)),
  onSetEditorOpen: callback => ipcRenderer.on('set-editor-open', (event, isOpen) => callback(isOpen)),
  onSetDisabled: callback => ipcRenderer.on('set-disabled', (event, disabled) => callback(disabled)),
  collectionCreate: name => ipcRenderer.send('collection-create', name),
  collectionCreateFromSelection: () => ipcRenderer.send('collection-create-from-selection'),
  collectionDelete: name => ipcRenderer.send('collection-delete', name),
  collectionRename: (oldName, newName) => ipcRenderer.send('collection-rename', oldName, newName),
  collectionMoveUp: name => ipcRenderer.send('collection-move-up', name),
  collectionMoveDown: name => ipcRenderer.send('collection-move-down', name),
  collectionReorder: names => ipcRenderer.send('collection-reorder', names),
  collectionSaveEditor: data => ipcRenderer.send('collection-save-editor', data),
  notifyCollectionsChanged: (collections, selectCollection) =>
    ipcRenderer.send('notify-collections-changed', collections, selectCollection),
  openCollectionEditor: collectionName => ipcRenderer.send('open-collection-editor', collectionName),
  openCollectionPrompt: (mode, currentName) => ipcRenderer.send('open-collection-prompt', mode, currentName),
  onInitCollectionEditor: callback => ipcRenderer.on('init-collection-editor', (event, data) => callback(data)),
  onUpdateCollectionEditorItems: callback => ipcRenderer.on('update-items', (event, data) => callback(data)),
  collectionEditorCancel: () => ipcRenderer.send('collection-editor-cancel'),
  collectionEditorSave: data => ipcRenderer.send('collection-editor-save', data),
  onInitCollectionPrompt: callback => ipcRenderer.on('init-collection-prompt', (event, data) => callback(data)),
  collectionPromptCancel: () => ipcRenderer.send('collection-prompt-cancel'),
  collectionPromptSubmit: name => ipcRenderer.send('collection-prompt-submit', name),
  onInitRenamePrompt: callback => ipcRenderer.on('init-rename-prompt', (event, data) => callback(data)),
  renamePromptCancel: () => ipcRenderer.send('rename-prompt-cancel'),
  renamePromptSubmit: name => ipcRenderer.send('rename-prompt-submit', name),
  showRenameDialog: data => ipcRenderer.send('show-rename-dialog', data),
  onRenameSubmitted: callback => ipcRenderer.on('rename-submitted', (event, data) => callback(data)),
  onInitPrompt: callback => ipcRenderer.on('init-prompt', (event, data) => callback(data)),
  promptResult: result => ipcRenderer.send('prompt-result', result),
  showPrompt: config => ipcRenderer.invoke('show-prompt', config),
  onInitInfo: callback => ipcRenderer.on('init-info', (event, data) => callback(data)),
  infoResult: () => ipcRenderer.send('info-result'),
  showInfo: config => ipcRenderer.invoke('show-info', config),
  onInitConfirm: callback => ipcRenderer.on('init-confirm', (event, data) => callback(data)),
  confirmResult: result => ipcRenderer.send('confirm-result', result),
  showConfirm: config => ipcRenderer.invoke('show-confirm', config),
  onInitWorkFolder: callback => ipcRenderer.on('init-work-folder', (event, data) => callback(data)),
  workFolderResult: result => ipcRenderer.send('work-folder-result', result),
  onExportBlueprint: callback => ipcRenderer.on('export-blueprint', (event, data) => callback(data)),
  exportBlueprint: (data, filename) => ipcRenderer.invoke('export-blueprint', data, filename),
  exportBlueprintGetPath: filename => ipcRenderer.invoke('export-blueprint-get-path', filename),
  saveBlueprintDirect: (data, filePath) => ipcRenderer.invoke('save-blueprint-direct', data, filePath),
});
